version: 0.2

phases:
  build:
    commands:
      - mvn clean
      - mvn install
      - chmod 755 deploy.sh
      - ./deploy.sh bookshelf-service dev us-east-2 14c5d91fa6bc973d5996cb259918853e7478f6f1
artifacts:
  files:
    - 'Dockerfile'
    - 'target/bookshelf-service.jar'
